###
GET http://localhost:3333/customer

###
GET http://localhost:3333/customer/2?yearMonth=2024-11

###
POST http://localhost:3333/customer
Content-Type: application/json

{
  "fullName": "Jhon Doe",
  "cpf": "012.345.678-0",
  "phones": [
    {
      "number": "11999999999",
      "description": "Residencial"
    }
  ],
  "address": {
    "publicPlace": "Rua Principal",
    "number": "123",
    "neighborhood": "Centro",
    "city": "São Paulo",
    "state": "São Paulo",
    "zipCode": "12345678"
  }
}

###
PATCH http://localhost:3333/customer/2
Content-Type: application/json

{
  "fullName": "Jhon Doe",
  "cpf": "012.345.678-09",
  "phones": [
    {
      "number": "11999999999",
      "description": "Residencial"
    },
    {
      "number": "11987097268",
      "description": "Particular"
    }
  ]
}

###
DELETE http://localhost:3333/customer/3
