// User Routes
### 
POST http://localhost:3333/signup
Content-Type: application/json

{
  "fullName": "Joao Vitor",
  "email": "joao.siben@email.com",
  "password": "123456789"
}

###
POST  http://localhost:3333/signin
Content-Type: application/json

{
  "email": "joao.siben@email.com",
  "password": "123456789"
}

// <------------------- Customers routes ----------------------->
###
GET http://localhost:3333/customers
Authorization: Bearer YOUR_TOKEN

###
GET http://localhost:3333/customers/1?yearMonth=2024-10
Authorization: Bearer YOUR_TOKEN

###
POST http://localhost:3333/customers
Authorization: Bearer YOUR_TOKEN
Content-Type: application/json

{
  "fullName": "Jhon Doe",
  "cpf": "012.345.678-0",
  "phones": [
    {
      "number": "11999999999",
      "description": "Residencial"
    }
  ],
  "address": {
    "publicPlace": "Rua Principal",
    "number": "123",
    "neighborhood": "Centro",
    "city": "São Paulo",
    "state": "São Paulo",
    "zipCode": "12345678"
  }
}

###
PATCH http://localhost:3333/customers/1
Authorization: Bearer YOUR_TOKEN
Content-Type: application/json

{
  "fullName": "Jhon Doe",
  "cpf": "012.345.678-09",
  "phones": [
    {
      "number": "11999999999",
      "description": "Residencial"
    },
    {
      "number": "11987097268",
      "description": "Particular"
    }
  ]
}

###
DELETE http://localhost:3333/customers/3
Authorization: Bearer YOUR_TOKEN

// <------------------------- Products routes ------------------------->
###
GET http://localhost:3333/products
Authorization: Bearer YOUR_TOKEN

###
GET http://localhost:3333/products/1
Authorization: Bearer YOUR_TOKEN

###
POST http://localhost:3333/products
Authorization: Bearer YOUR_TOKEN
Content-Type: application/json

{
  "name": "smartphone",
  "description": "smartphone from that well-known brand",
  "sku": "100100",
  "price": 7000.00,
  "amount": 15
}

###
PATCH http://localhost:3333/products/1
Authorization: Bearer YOUR_TOKEN
Content-Type: application/json

{
  "amount": 20
}

###
DELETE http://localhost:3333/products/1
Authorization: Bearer YOUR_TOKEN

// <----------------------------- Sale routes ----------------------------->
###
POST http://localhost:3333/sale
Authorization: Bearer YOUR_TOKEN
Content-Type: application/json

{
  "amount": 1,
  "customerId": 1,
  "productId": 1
}