services:
  mysql:
    image: mysql:oraclelinux9
    # restart: unless-stopped
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: store
    volumes:
      - db:/var/lib/mysql
    networks:
      - store

  api:
    build: 
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3333:3333
    depends_on:
      - mysql
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=store
      - NODE_ENV=development
      - APP_KEY=3SOADhajxhN6oYFN5_jDUhrdZc2Q3g8C
      - LOG_LEVEL=info
      - DB_DATABASE=store
      - SESSION_DRIVER=cookie
    volumes:
      - ./:/app:delegated
      - /app/node_modules
    networks:
      - store
    # command: sh -c "./wait-for-it.sh mysql:3306 -- node ace migration:run && npm run build && npm start"


volumes:
  db:
    driver: local

networks:
  store:
    driver: bridge